services:
  postgres:
    restart: unless-stopped
    logging: &logs
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  redis:
    restart: unless-stopped
    logging: *logs
  anvil:
    restart: unless-stopped
    logging: *logs
